language: node_js
node_js:
- 5.5.0
install:
- npm install
script:
- npm run lint && npm test && npm run build
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: connectv2.topcoder-dev.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: dev
- provider: s3
  cache_control: private, no-store, no-cache, must-revalidate, max-age=0
  detect_encoding: true
  access_key_id: $QA_AWS_KEY
  secret_access_key: $QA_AWS_SECRET
  bucket: connectv2.topcoder-qa.com
  skip_cleanup: true
  local_dir: dist
  on:
    branch: qa
env:
  matrix:
    - CXX=g++-4.8
  global:
    # AWS_KEY
    - secure: Ufq/BPpNz+a9G+vkCKGcO+2/A3gR+i1TTKZsrjQLLU19S+UnfBGaDo87VfK5xB+hNndeKdxkuE6mqCF7ifuNrKfgG+L7oFcgcGy4mXiuJgyKWN+pheNdq2C4MDJ2uBHxcZDyRYuMA8pf+qLa0nQzUsHxFXurGLqvYvOOOWqWURCQ2FzyT+HWmLGdda0eRbA6wNO90xij07IM2Mv6nH8kgHb8NeNzVz/7jTsw0saBzDJ4eipzyoKwlKtTx3qgPyEi48EhTBQg4w6En4bgF6BMGSUvpyzydzT3SHC87WyBL5UCof3u17eD5kzO/Snw9gVWhCiavIkZXghpa7HqxMPaL/yVa+zENIbK2qE7bcrRhogerOpvR6ckuF5gby8+idCSf89xvCh+BBYxY998N6UDheeJcERrgOK8A/GgUodvSOciDPGA43T+96hOUQaRJHhWahBRs5VGYxL61Xxerq9Evsfin5Qf6HA/wOhvKfRr3DjOzyQfAtK7k1GjR3ElsWYgfcSibJsLcf6iX/WtvUWem75UW+xdbHCrLb0DonN4dVW8r1DmUrhm+OhxXOthE4VpDRg7Z7Zvd3TIwPPAzvnEL4pzNvt+ka//kykw8ZC6iy9wSnjesrg33vYnjIWsMMwoa20QwuFyL1OD+tff4PYATrcmYJsxfjJJ9LvmYcpYk1w=
    # AWS_SECRET
    - secure: refchMJJQIdktcu8BtCePYzRB8niSyJLROnrLfxLWAOA+/LampzdGAwwQS355sgakQWO27PzQ4FEFLxGbZOidjuNo0+UnDQjcmkCELvNiblWB6/I0nnbC/fupB16wlvQe7gBXQs46EnGkIYrxfaL2NPwdpSUoPQDM9H8NcVbW/E7JfkpT6jaq7U9XEyFUlad5qiRdxUA4IHnQxum6tVGZoyM4PYL738Xb+GhWe/LLyx8eTPt5Kd3zet9Dti7oIlQhxLLcSQEGOpSvlgnwXMGSgDNOLRtHvr8UQ+jUglIBhfJZWtcjwk5pFyXuP/29FgKt8dR1396B3IOlemRen4q8+4upNCzLjnHZQabzdP3p1T/mrkV8LbyRPU+6kx1kFNdkaX5KzcXIa/9fYKpf1im5zePGUTeEEaYpz/3+GKYFb4foMD/mQekNyLSQjt4MA7U1lxtamd+m4plbVQayIWRnzHPo1e9YrMNFVkG/sK9SAjjeKJ1nLzdWIKJUrGz4io+fK2A6BgP1zgvs4BqLKs2rca0wDUxbl3NkG5CDX9gdfw25VhwlIRb3izf9w0+edDo7iq+QbL8t4hwsagSOoWQMTLwy0VCIUFSjYBewBvW1R2DzhjXgZcv9msm8Ik9p0W7Y0IEyszwrgrP/ITT3GR8cFOjseSJ0OGdeoWYoxqsMAc=
    # QA_AWS_KEY
    - secure: R8NFFjS2HbS4W6URhpkqaoSP6rwuLqMciouxujQNG8H4RA2y+6W6JgHtjvRIdTUkDSGEaNs5OLBcFacU3/z4BfvmdjnLVlb4rqnPNXitIduDJJtHGBIlVmC1RFKI0S5zIma0x3gxZOx+j8T7s+pzyIISIMqfklF3GPOpJoGy0apwfnzLhHfMwI2OdeK8BchpZBItfl3El9/AdEdBttuvuzF3DHzAC7RtcY6ol5UoM0klwiJqvTeF2jBBzQ0uOO9eSiG3Y13S+sP8lo6WUvPP+KBWOHoDKV0lI2PgNn7Ngw04GQRt1RHP1s0Ewio448aGEUsOoCTqAwfEmsxVBxp01/gxU45NQ58wNovNLmdzKI5CtZVOSDrtqyvsh/wV4BWDlu8Y6+bRQCfvkJoDjmN25RonqjHrvpjRw+rz4O10w3DPJYq4EC3QX0urLUhj8yzoa5uBC9i6llYLjGo4RPuXV4tzQwhLcWNakZ38lGQkYK98GNylwMZYQLZ67/+D5KGSnqZ4lWggPdFUnOCDgdi4Q9Cg99g9p8tccRTTdLDkXAM56aFvzr2PvZBei3PxDyY1Ggr1qdwDZ2rN7rE+3aTA0NeIK/2U8LRVxt/daWf3EzwDkI9zWbgDjUslYjdhSYp5UpzmnpKTh1XxzUe5sUslwemgM9Hxp0zP0bxg/02YfRc=
    # QA_AWS_SECRET
    - secure: VvGuwmjezGoVrpYjnN+vcJaS9Qq60fd25WwUhtHxUh8yfluS+shGEJFhDhHa9sUmpISB3TEgTvIhZP9z8dzKJ+Y4aM+3A5nCq0DdIU5IhinxXlnWkLfKycZpJxnG0c6Ji/qbmwesZqveU8jKcH8h3OVFktzzYO3VTE13kjIy6TmveccUh0Daq+gY/3AHm1Bw1vl02X5wpJjEvHTLHzQ8HDkjayDDnngLq/Tkpg7mTGxCmjhilZCC5R+M5qG2NWUO6YJiVLLsmG18ncX0EPlzsAzX2eHbID0cNznlkdm3rf4+PRgwvJBrrv6AmJuSkjHhnmRRhxijIw9e+/PzIK5Lu1rYtWe48FQ0+/thKaQwegnWepxNxidpoI/nh98Y9fldwHbBNuFWURLFv1U7FufUIqs78eyIzjJRcHrhaMe/dmWZNeYTmiuBQ154wztsB/RsYbcMiFVQnt2H/Y6kFZHUh0VYp+kVKs5nqiQu3JWj9HhlF2de+GyIlgJf1rAcrMoDITKn37ou+R+OPpe3qI2g3Prnfr6RC7VrLdHkf/eMGEodHt9F8w/g9LdXHlW4lq50iYdYQ2o8GxTsLiMBdzQ9avVJyO8t5hJvxY9S21+drZUENsL34WBE8rv0gLX+j2Hq4M01rGvtH5Z26SD0TZuIXGhB3tSy0Uh/BHhyH/HVSKI=
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
